### ISSUE TITLE
Conditionals not working in symbols

### ISSUE THREAD

**Issue by andyra** [preciousforever/data-populator#104]
Conditionals don't seem to work within symbols (but work fine otherwise). An example symbol:

- A text layer with `{name}` as the content will output, for example, "Bill"
- A shape layer with the name `#hide["{name}".length > 0]` shouldn't be visible since {name} has a length of 4 (in this case).

Software versions:
- Sketch 45.2
- Sketch Data Populator 2.2.0
- macOS 10.12.5

**Comment by fonograph** [comment]
Confirmed using Sketch 46.2 / plugin 2.2.0. If I simply detach all my symbols, conditionals works fine.

**Comment by andyra** [comment]
This is still an issue in Sketch 49

**Comment by endswithak** [comment]
I was able to fix this by adding `Actions.performActions()` to the text and image loops within the `populateSymbolLayer` function. I also added the group layers loop to handle subgroup actions within the symbol.

```javascript
  //populate text layers
  let textLayers = Layers.findLayersInLayer('*', false, Layers.TEXT, symbolMaster, false, null)
  textLayers.forEach((textLayer) => {
    populateTextLayer(textLayer, data, {
      trimText: opt.trimText,
      insertEllipsis: opt.insertEllipsis,
      defaultSubstitute: opt.defaultSubstitute,
      overrides: overrides
    })

    // NEW
    Actions.performActions(textLayer, data)
  })

  //populate images
  let imageLayers = Layers.findLayersInLayer('{*}', false, Layers.SHAPE, symbolMaster, false, null)
  imageLayers = imageLayers.concat(Layers.findLayersInLayer('{*}', false, Layers.BITMAP, symbolMaster, false, null))
  imageLayers.forEach((imageLayer) => {
    populateImageLayer(imageLayer, data, {
      rootDir: opt.rootDir,
      overrides: overrides
    })

    // NEW
    Actions.performActions(imageLayer, data)
  })
   
  // NEW
  //perform actions on sub-groups
  let groupLayers = Layers.findLayersInLayer('*', false, Layers.GROUP, symbolMaster, false, null)
  groupLayers.forEach(function (groupLayer) {
    Actions.performActions(groupLayer, data)
  })
```

**Comment by nitrada** [comment]
@andyra @fonograph we'll actually not be able to make #show, #hide and #delete actions work within symbols. but #swapSymbol now works well in nested symbols and also with Libraries. for now, you could create a condition that swaps to an "invisible" symbol, but we're going to make it possible to swap to _None_ (= no symbol selected) with – most likely – the syntax eg. `[#swapSymbol["{name}".length > 0]` — so if you don't provide a symbol name like `[#swapSymbol["{name}".length > 0, symbolname]`, it will swap the symbol to _None_

**Comment by nitrada** [comment]
please check out v3.0.3!
https://www.datapopulator.com/sketch/changelog.html
