### ISSUE TITLE
Multi-Artboard Support

### ISSUE THREAD

**Issue by alirenttrack** [preciousforever/data-populator#107]
I can only run the plugin per arboard - would it be difficult to allow multiple artboards? 

![multi-artboard](https://user-images.githubusercontent.com/26285333/30036102-c9127f5a-9175-11e7-9da5-66b7f392d326.gif)

**Comment by lukasondrej** [comment]
Hey @alirenttrack, I've looked into this issue in detail now and I understand what you'd like to achieve but there's a conceptual issue with it. Let me explain:

When you check 'Create grid', Data Populator only considers the top-left artboard in your selection. It then creates the grid using that single artboard (or layer, group, etc).

When multiple artboards are selected, all apart from the top-left are discarded as per the intended behaviour. The reason for this is that if you create a grid and then want to change the number of rows/cols or margins, you can simply repopulate again and a new grid will be created using the original single artboard.

This means that we'd need to change this behaviour to instead create a grid originating from each selected artboard/layer. That's something that needs further discussion.

What do you think @nitrada, @rockitbaby?

**Comment by alirenttrack** [comment]
Hi @lukasondrej

Thanks so much for following up on this issue. I understand the behavior. If you allowed it - a grid with multiple origin points (top left) would overlap. 

May I suggest that the only conditional change would be that if the plugin recognized you selected multiple art boards, it simply would only offer you a column or a row - not a grid? 

In the example gif above, I would choose from column as opposed to row and that would then populate a coloumns of artboards.
