### ISSUE TITLE
#delete[condition]

### ISSUE THREAD

**Issue by alirenttrack** [preciousforever/data-populator#108]
If I use the #delete["{column-title}" == "cell"] on an artboard, it works to delete the artboard, however, the artboards that follow that deleted artboard, none of the {placeholders} work.

For example with 6 artboards:

Artboard 1 - Shows & all {placeholders} work.
Artboard 2 - Shows &  all {placeholders} work.
Artboard 3 - Deletes (As intended using #delete[condition])
Artboard 4 - Shows but no {placeholders} work.
Artboard 5 - Shows but no {placeholders} work.
Artboard 6 - Shows but no {placeholders} work.

**Comment by alirenttrack** [comment]
Note: this only applies to Artboards.

**Comment by nitrada** [comment]
please see last comment in #104
