### ISSUE TITLE
Group Name via {placeholder}

### ISSUE THREAD

**Issue by alirenttrack** [preciousforever/data-populator#109]
Currently if you name the Artboard {placeholder} and run the plugin, the arboard names update. However, if you name a Group {placeholder} and do the same, the Group does not update with the name.

**Comment by junaid2ali** [comment]
@alirenttrack did you find a fix for this? Thanks.

**Comment by alirenttrack** [comment]
No, I didn’t. However I worked around the issue in my workflow.

**Comment by junaid2ali** [comment]
Can I ask what your work around was? Thanks.

Sent from my iPhone

On Feb 21, 2018, at 10:46 AM, alirenttrack <notifications@github.com<mailto:notifications@github.com>> wrote:

No, I didn’t. However I worked around the issue in my workflow.

**Comment by nitrada** [comment]
It's not working, since a Layer Group is treated like a regular Layer. But I agree it could be helpful in some cases – and since we also added that support for Artboards…
