### ISSUE TITLE
Possibility to calculate values?

### ISSUE THREAD

**Issue by niksmac** [preciousforever/data-populator#113]
Some calculations like `{rowvalue} * 12`. Is it possible?

**Comment by nitrada** [comment]
@niksmac can you provide an example use case?

**Comment by niksmac** [comment]
Sure.
Lets say I am building an invoice. Where I want the quantity to be multiplied by the rate to get them price. Makes sense?

**Comment by nitrada** [comment]
Maybe there should be a _Filter_ that allows basic mathematical operations:

`{quantity * rate}` € → `{3 * 4,99}` € → 14,97 €

`{rowvalue * 12}` → `{10 * 12}` → 120

$`{=SUM(value1,value2,value3)}` → $`{=SUM(10,20,30)}` → $70

I guess this would also need rounding and decimals parameters then…

**Comment by nitrada** [comment]
@niksmac maybe you're interested in working on such filter? I think most things are already there and could be integrated via existing frameworks. Data Populator's API is pretty basic and open as it is all based on JavaScript…

**Comment by niksmac** [comment]
@nitrada Yep, but only after a month.

**Comment by nitrada** [comment]
that would be great!

**Comment by nitrada** [comment]
@niksmac did you look into adding those basic math filters? ;-)
