### ISSUE TITLE
Nested objects works, does the same works for nested arrays inside an object?

### ISSUE THREAD

**Issue by csantiago132** [preciousforever/data-populator#115]
Ok, just to finally wrap my head around this plugin; as per the [closed issue 69
](https://github.com/preciousforever/sketch-data-populator/issues/69), 
you can nest objects inside objects like so (and this works)

     {
            "presets": {

            "preset_value": "Today"

        }
        
    
    }

but i cannot nest an array inside an object (to populate data for symbols grouped under an object) like this one:

   
      `{
        "presets": [

            {

            "preset_value": "Today"

            },

            {

            "preset_value": "Yesterday"

            }

        ]
            
    }`

meaning, that if i want to populate symbols, i have to have a separate file saved as an array of objects to populate them. or i simply do not know how to nest arrays inside symbols?

**Comment by ritobruno** [comment]
How is this issue? 
Is it possible now to add an array nested inside an object? Or for now the json needs to be more simple?

**Comment by metalhaze** [comment]
@csantiago132 I mentioned this on the closed issue but posting here as well....

You don't navigate arrays the same way you navigate Objects.

presets[0].preset_value    --> should give you "Today"
