### ISSUE TITLE
Doesn't work with Symbols in Sketch 49

### ISSUE THREAD

**Issue by andyra** [preciousforever/data-populator#123]
I updated to Sketch 49 and Data Populator no longer applies symbol overrides. If I detach the instance from its symbol, Data Populator works as expected.

**Comment by andyra** [comment]
Sorry, after closing Sketch and reopening, things are working as expected. Not sure why, but: phew!

**Comment by hlambert** [comment]
I cannot get this to work. @andyra: Did you change anything to get it working?

**Comment by andyra** [comment]
Sort of. I found that symbols I made before the v49 update oftentimes don't work with Data Populator. Some do and some don't and I can't tell what the difference between them is—some are even requesting the exact same JSON data fields, just arranged differently.

I've found that Data Populator _usually_ works if you recreate the symbols. You can't just delete the layers within the existing symbol and add them again, you have to actually create a brand new symbol.

I've had a couple times, however, where even new symbols stop working with Data Populator within a certain Sketch file. My way around this is to create a new Sketch file, insert the new symbol, run Data Populator, then cut/paste that into the file I really want it in. Super annoying, but it's better than nothing!

**Comment by hlambert** [comment]
Thanks for your reply.

I have nested symbols, som copying and pasting symbols around is not really a feasible solution.

In addition to that, I have been having problems with InVision Craft sync as well.

**Comment by setheryb** [comment]
I'm having the same problem. I created the symbols today and went to populate the data and am getting nothing.

**Comment by patowod** [comment]
Same here, restarting Sketch doesn't work either. When detaching the same symbol it works fine. The idea of then creating a new symbol is nice but doesn't seem to work on my end, either. Any ideas, greatly appreciated.

**Comment by nitrada** [comment]
@lukasondrej can you look into the symbols in Sketch 49 issue?

**Comment by pieterh83** [comment]
I'm having the same problem for #hide and #show functions of layers inside a symbol. If I populate the data the layers with the #hide and #show layernames don't work anymore.

**Comment by andyra** [comment]
@pieterh83 Unfortunately, conditionals don't work with symbols right now. I have a separate issue for that here: https://github.com/preciousforever/sketch-data-populator/issues/104

**Comment by lukasondrej** [comment]
There was a similar issue at some point before when Sketch got updated. It's most likely because of a changed internal structure of how symbol overrides are stored on symbols. I will investigate.

**Comment by nitrada** [comment]
@lukasondrej please note that it was already an issue with sketch 45 https://github.com/preciousforever/sketch-data-populator/issues/104

**Comment by hlambert** [comment]
Just tried getting it to work in Sketch 50. The changes and fixes to the symbols in the latest release doesn't seem to fix the issue. Just FYI

**Comment by nitrada** [comment]
@andyra  @hlambert @setheryb @patowod @pieterh83 please update to version 3.0.2 and tell us if it now works for you! 

https://www.datapopulator.com/sketch/
