### ISSUE TITLE
Freezes when JSON contains Emoji

### ISSUE THREAD

**Issue by philipkopylov** [preciousforever/data-populator#150]
**Describe the bug**
Freezes when JSON contains Emoji.

**To Reproduce**
1. Create JSON with any Emoji in it
2. Try to populate symbol
3. Freeze

**Environment (please complete the following information):**
 - macOS Version: 10.13.1
 - Sketch Version 48.2
 - Plugin Version 2.3.4

**Comment by nitrada** [comment]
@lukasondrej might be an easy fix?
