### ISSUE TITLE
Images not populated in Sketch 52

### ISSUE THREAD

**Issue by classyentrepreneur** [preciousforever/data-populator#154]
Images aren't getting populated in the latest version of Sketch :(

**Comment by napathello** [comment]
same problem

**Comment by classyentrepreneur** [comment]
@napathello, let's hope for an update. It prevents me from updating to the latest version of Sketch.

**Comment by nitrada** [comment]
hey @classyentrepreneur @napathello, a fixed has been released (v2.3.5). Get the update via "Plugins > Manage Plugins…" or here: https://github.com/preciousforever/data-populator/releases/tag/v2.3.5

Let us know if it works for you and close the issue.

**Comment by classyentrepreneur** [comment]
Thanks for the fix.

I didn't notice Sketch 52 added the custom Data Feeds, so I've converted my document to support their core feature, and am not able to check your plugin :(
