### ISSUE TITLE
image not loading

### ISSUE THREAD

**Issue by defawlt** [preciousforever/data-populator#156]
**Which version of the plugin are you using?**
[ ] Data Populator for Adobe XD

**Describe the bug**
When using the "Populate with preset" option it doesn't seem to want to load {image} from the url. It just loads the url as plain text (or rather text styled however I have it in the XD file).

**To Reproduce**

Create a {image} placeholder
1. Go to 'populate with preset'
2. Click on 'populate'
3. See error

**Expected behavior**
An image should be loading in the appropriate tag
<img width="561" alt="screen shot 2018-10-18 at 10 04 41 pm" src="https://user-images.githubusercontent.com/967810/47180906-eab65700-d321-11e8-85db-c9328756656e.png">

**Screenshots**

**Environment (please complete the following information):**
 - macOS Version: [e.g. macOS High Sierra 10.13.5]
 - Sketch Version [e.g. Sketch 52.2] or Adobe XD Version [e.g. Adobe XD 13.0.0.0]
 - Plugin Version [e.g. 3.0.0]

**Comment by defawlt** [comment]
> @defawlt what type of object/layer are you using with the {image} placeholder? can you add a screenshot?

@nitrada Here' s screenshot of the 3 basic steps as well as the preset JSON file i'm trying to use. I've tried it as a text layer, with a repeat grid as well as inside of an image mask for the heck of it. Hope this helps explain it better.

![1-setup](https://user-images.githubusercontent.com/967810/47216929-f6982c80-d3a6-11e8-97c3-5c37e735fc32.png)
![2-json file](https://user-images.githubusercontent.com/967810/47216930-f6982c80-d3a6-11e8-982b-51825e6b9e3d.png)
![3-results](https://user-images.githubusercontent.com/967810/47216932-f6982c80-d3a6-11e8-815b-088ab258d263.png)

**Comment by nitrada** [comment]
@defawlt you need to use {image} as the name of an image mask (shape layer).

**Comment by defawlt** [comment]
@nitrada That worked, I was naming the wrong thing. I was naming the layer mask rather than drilling down to the actual shape layer. Thanks for your help!

**Comment by nitrada** [comment]
@defawlt happy to help. that’s valuable feedback to hear, thanks for that – it’s not yet obvious how to do it apparently :)
