### ISSUE TITLE
Nested Override Symbol doesn't populate

### ISSUE THREAD

**Issue by cat-martiancraft** [preciousforever/data-populator#157]
**Which version of the plugin are you using?**
 [3.0] Data Populator for Sketch

Question:
Thank you for making this plugin! It's saving me a ton of time getting this set up! I have a few questions about this limitation...

I'm working with a shared library where I'm placing my symbol. My symbol has a background and a symbol inside to dictate how many digits in the number field. I have it named "1 digit" with option to override "2 digit" and "3 digits", my JSON is called {one} {two} {three}.

What I'm trying to do is create a Table Cell. Each cell has the option of selecting the number of digits plus the styling. When I have the base symbol placed in my file, JSON would successfully override the symbol for what's placed as default, 1 digit. 

If I override the symbol, ie. "base was 1 digit, I override it to 2 digit", the JSON will no longer populate. There's also something strange about, if I made the base 2 digits, then override it to 1 digit, it will remove 1 number as it increments down, but would not be able to repopulate if it's switched back to 2 digits.

Am I doing this wrong?

Example to illustrate below:

![screen shot 2018-10-20 at 2 52 37 am](https://user-images.githubusercontent.com/11272475/47252445-44e31500-d413-11e8-8fa9-5ec15a841580.png)

![screen shot 2018-10-20 at 2 55 14 am](https://user-images.githubusercontent.com/11272475/47252464-95f30900-d413-11e8-990c-6264fc59aa01.png)

**Environment (please complete the following information):**
 - macOS Version: macOS High Sierra 10.13.6
 - Plugin Version 3.0.0

**Comment by nitrada** [comment]
@cat-martiancraft could you provide the sketch and JSON used?

**Comment by cat-martiancraft** [comment]
@nitrada Thanks for the fast reply :) I've attached the zip here. I've noticed that it will populate if I detach the symbol :)

[git sample file.zip](https://github.com/preciousforever/data-populator/files/2498192/git.sample.file.zip)

**Comment by nitrada** [comment]
@cat-martiancraft so your expectation would be that after populating, when switching the embedded symbol (via the override inspecator) from e.g. "number 1" to "number 3", that the value for {three} should be visible?

**Comment by cat-martiancraft** [comment]
yes, is that possible? 😬

**Comment by nitrada** [comment]
apparently not at the moment :-P

but there are another few issues with (nested) symbols we need to look into (e.g. #123 and #104). could you have a look, @lukasondrej?

**Comment by cat-martiancraft** [comment]
Appreciate it! My issue sounds just like #123 except I haven’t used this
plugin until now on current version of sketch.

**Comment by nitrada** [comment]
@cat-martiancraft what you need is what's described in #94: there would be no {placeholder} _inside_ the symbol, you would just put {one}, {two} and {three} in the overrides for the very same symbol.

as commented over there, we'Re trxing to get this running in the next version…

**Comment by cat-martiancraft** [comment]
@nitrada Thank you Nitrada. #94 looks like it would be a great addition.

**Comment by nitrada** [comment]
please check out v3.0.3!
https://www.datapopulator.com/sketch/changelog.html

**Comment by benjigreig** [comment]
Hey there, Have 3.0.3 but have the same issue with overrides. The nesting level is higher though 4-5 symbols deep. Happy to send over example file to test the issue with.

**Comment by nitrada** [comment]
@benjigreig please describe your issue in more detail and send over that demo file to feedback@datapopulator.com
