### ISSUE TITLE
Data Populator on Slack

### ISSUE THREAD

**Issue by nitrada** [preciousforever/data-populator#161]
We created a Slack workspace for Data Populator over the weekend. Please keep posting your Bugs and Features Requests as GitHub issues. 

But if you have general questions or suggestions you'd like to discuss, please use Slack. Also, we have a lot of thoughts about the future development of the plugin we'd like to share and hear your feedback on over the coming weeks.

Use this link to join:
https://join.slack.com/t/datapopulator/shared_invite/zt-6o73rzvp-P8eFKmujQWeqTtYSDL11wA

Talk to you soon!

**Comment by aiancuevc** [comment]
The invite link is no longer active! 🚨

**Comment by tralston** [comment]
@nitrada Is this slack channel still open? The invite link is expired 😢

**Comment by nitrada** [comment]
@tralston it's working again: https://join.slack.com/t/datapopulator/shared_invite/zt-6o73rzvp-P8eFKmujQWeqTtYSDL11wA
