### ISSUE TITLE
#swapSymbol does not work with Sketch Libraries

### ISSUE THREAD

**Issue by JaccoSchumacher** [preciousforever/data-populator#162]
**Which version of the plugin are you using?**
[x] Data Populator for Sketch

**Describe the bug**
The #swapSymbol conditional action does not work with Sketch Libraries. It seems this is because the symbol it needs to swap to is not present in the sketch file, but only in the linked Library file. It cannot find the symbol to swap to.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup attached TestLibrary.sketch as a library in sketch 
[SymbolSwapTest.zip](https://github.com/preciousforever/data-populator/files/2544904/SymbolSwapTest.zip)
2. Open TestFile.sketch (a regular sketch file)
3. Use attached JSON file to populate the symbol "List-item" in TestFile.sketch
4. Result should be: Text is populated correctly, but symbol is not.

**Expected behavior**
I would expect Data Populator to find the symbol from the Sketch library that is linked to the regular sketch file.

**Environment**
 - macOS Version: macOS Mojave 10.14
 - Sketch Version: Sketch 52.3
 - Plugin Version: 3.0.1

**Additional context**
I tried to place the name of the sketch library in front of the path: #swapSymbol[true, TestLibrary/Icons/{icon}] but that didn't work. This is also not how I would like it to work, because I work with the version control app Abstract. Abstract places a suffix after filenames (with the branch name), so my library files never have a static filename (as it is constantly updated).

**Comment by nitrada** [comment]
@JaccoSchumacher should work with v3.0.2 – please check it out and let us know!
https://www.datapopulator.com/sketch/

**Comment by JaccoSchumacher** [comment]
It works! Thanks for resolving this so quickly! Amazing support

**Comment by junaid2ali** [comment]
> It works! Thanks for resolving this so quickly! Amazing support

@JaccoSchumacher I also use Abstract and am trying to swap symbols from a linked library. I have my JSON file setup as:
[
 {
   "Header": "Good Morning Breakfast",
   "Main": "Beef (Master @ 5ce0d62)/Relative/Hamburger"
 },
 {
   "Header": "Time for Lunch",
   "Main": "Beef (Master @ 5ce0d62)/Relative/Cheeseburger"
 },
 {
   "Header": "Yes, it's Dinner Time",
   "Main": "Chicken Fish (Master @ 5ce0d62)/Relative/Fish"
 }
]

In my sketch file I have the symbol layer as: #swapSymbol[true, {Main}] however it is not working, only the text is displaying as variable.

Can you assist.

Thanks.
