### ISSUE TITLE
Unique values within multiple instances of the same symbol

### ISSUE THREAD

**Issue by guymeyer** [preciousforever/data-populator#163]
**Which version of the plugin are you using?**
[3.0 ] Data Populator for Sketch

**Is your feature request related to a problem? Please describe.**
As someone who uses atomic design principles, it would be awesome for Data Populator to work with this layer structure. Right now when I run Data Populator on a symbol used multiple times within a larger symbol, the returned values are the same repeated over and over.

**Describe the solution you'd like**
* Lets say I have a symbol with a {label}
* I import 4 instances of said symbol into a new symbol
* When I run data popular, the {label} should receive unique values from the data source.

**Describe alternatives you've considered**
The only other way to do this I can imagine is not having my instances within a larger symbol. 

**Additional context**
I feel like this has probably been asked, but I cannot seem to find a topic covering it. Apologies if this is a beaten horse.

**Comment by nitrada** [comment]
@guymeyer i’d say that’s covered in #94 – please verify

**Comment by guymeyer** [comment]
@nitrada I saw #94  and agree its close. But I think the difference is my case has the same placeholder values vs unique placeholders within a parent symbol. For instance:

![image](https://user-images.githubusercontent.com/1927/48269305-de8f5800-e3fc-11e8-8777-afcaecc7703b.png)

The parent symbol is holding 4 instances of the same symbol. 

When I run Data Populator, this is the output

![image](https://user-images.githubusercontent.com/1927/48269380-0da5c980-e3fd-11e8-8bee-bb997010c842.png)

Based off this JSON

`[
	{
		"label": "Cat"
	},
	{
		"label": "Dog"
	},
	{
		"label": "Fish"
	},
	{
		"label": "Pig"
	},
	{
		"label": "Snake"
	},
	{
		"label": "Turtle"
	}
]`

**Comment by guymeyer** [comment]
btw, I shouldn't even be asking for this. The plugin is already fantastic.

**Comment by nitrada** [comment]
@guymeyer your feedback is priceless :)

so your problem rather is that although there are multiple actual instances of a symbol within a symbol, from data populator's perspective it's treated as a single instance (= the one from the parent symbol).

this is exactly the same if you just group multiple symbols and populate the group, not select all symbols one by one and populate.

so I guess your issue is rather related to #115 

@lukasondrej what's your thoughts?

**Comment by guymeyer** [comment]
@nitrada I *think* thats on the right track, either way I'll leave it to you to keep this open or not. I think the visual help a bit more clearly :)

**Comment by nitrada** [comment]
please check out v3.0.3!
https://www.datapopulator.com/sketch/changelog.html

**Comment by elagha** [comment]
Sorry for commenting on a closed issue... I have the same request as @guymeyer, but I don't believe this works in v3.0.3. I still face the same issue when trying to populate a symbol's child symbols. My JSON file is structured in the same way as @guymeyer's example:

> `[ { "label": "Cat" }, { "label": "Dog" }, { "label": "Fish" }, { "label": "Pig" }, { "label": "Snake" }, { "label": "Turtle" } ]`

Should I structure it differently for this to work?

**Comment by bpica168** [comment]
Still having this issue. Exactly as the OP describes.
