### ISSUE TITLE
Adobe XD text area trim / ellipsis not working

### ISSUE THREAD

**Issue by codeth** [preciousforever/data-populator#167]
**Which version of the plugin are you using?**
Data Populator for Adobe XD

**Describe the bug**
The "Trim overflowing text" and "Insert ellipsis after" options are not working in Adobe XD.

**To Reproduce**
1. Create template which includes XD Area Text fields with placeholders
2. Use "Populate wth JSON"
3. Under "Data Options", select the trim and ellipsis options
4. Click Populate
5. Text is populated but not truncated. The placeholder is replaced with the full string and XD Area Text naturally hides the overflow from view.

**Expected behavior**
Placeholders should be replaced with text that has been trimmed and appended with an ellipsis.

**Environment (please complete the following information):**
 - Windows 10
 - Adobe XD v13.1.32.8
 - Plugin v1.1.4

**Comment by spoon98** [comment]
Any updates on this, I'm facing the same issue
