### ISSUE TITLE
Trouble with Plugin Command

### ISSUE THREAD

**Issue by junaid2ali** [preciousforever/data-populator#169]
**Which version of the plugin are you using?**
[3.0.3] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Describe the bug**
I am trying to run a command in the Automate Plugin.

**To Reproduce**
<img width="836" alt="screen1" src="https://user-images.githubusercontent.com/6130499/49777492-5daad100-fcc6-11e8-91b2-18c986b89e1b.png">
<img width="852" alt="screen2" src="https://user-images.githubusercontent.com/6130499/49777491-5d123a80-fcc6-11e8-96ec-12684f26051d.png">
<img width="788" alt="screen3" src="https://user-images.githubusercontent.com/6130499/49777489-5d123a80-fcc6-11e8-96dd-b882e79a2b4b.png">
<img width="1322" alt="screen4" src="https://user-images.githubusercontent.com/6130499/49777488-5d123a80-fcc6-11e8-9faa-95c08f007182.png">
**Expected behavior**
The Plugin returns a message saying command could not run.

**Screenshots**

**Environment (please complete the following information):**
 - macOS Version: [e.g. macOS High Sierra 10.13.5] HighSierra
 - Sketch Version [e.g. Sketch 52.2] or Adobe XD Version [e.g. Adobe XD 13.0.0.0]
 - Plugin Version [e.g. 3.0.0]

**Additional context**

**Comment by nitrada** [comment]
@junaid2ali please give more context. what are you trying to achieve and what doesn’t work?

**Comment by junaid2ali** [comment]
@nitrada 
I am pulling data from my json file which works. I have blocks of paragraphs where some records do not have all the lines in those paragraphs, they result in a hidden layer. I would like to run that plugin after it populated the grid to remove all the hidden layers.

**Comment by nitrada** [comment]
@junaid2ali still don’t get it. can you maybe record a video?
