### ISSUE TITLE
'Maximum Characters' feature not working with numbers (possible feature request?)

### ISSUE THREAD

**Issue by bgott** [preciousforever/data-populator#170]
**Plugin Version**
Data Populator for Sketch 3.0.3

**Description**
The 'maximum character' feature doesn't work with number values.

**Proposition**
If there are plans to add filtering functionality for data inputs as 'numbers' (examples: greater than, less than, parity checking, etc.) then the 'max' filter should remain as-is, handling strictly 'string' inputs. However, if those features aren't in the pipeline, I'd propose 'number' inputs be converted to 'strings' before populating placeholders, such that the 'max' filter can be taken advantage of.

**Reproduction**
1. Go to the Boarding Pass example in the demo document
2. Set data URL to 'https://www.datapopulator.com/demodata/boardingpass.json'
3. Change {qr.id} to {qr.id | max 5}

**Expected behavior**
The input value to be trimmed to the input number of characters, whether the input is of type 'string' or 'number'.

**Environment**
 - macOS Version: macOS Mojave 10.14
 - Sketch Version: 52.5
 - Plugin Version: 3.0.3

**Comment by nitrada** [comment]
@bgott we’d actually love to add numbers specific filters at some point – even some basic calculation would be great (see #113). would you be up helping here? :-)
