### ISSUE TITLE
nested symbols being changed 

### ISSUE THREAD

**Issue by tsheiner** [preciousforever/data-populator#171]
**Which version of the plugin are you using?**
[x ] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Describe the bug**
Data populator changes the override value on a nested symbol that, as far as I can tell, does not have a name that should cause it to be changed.

**To Reproduce**
The symbol I am populating has this schema:
![screen shot 2018-12-18 at 10 56 42 am](https://user-images.githubusercontent.com/839128/50177267-65fe9f80-02b6-11e9-9f94-14e6f2922508.png)

The selected nested symbol, named 'menu' has this override structure:

![screen shot 2018-12-18 at 10 57 14 am](https://user-images.githubusercontent.com/839128/50177289-79aa0600-02b6-11e9-8f87-b2dcc42baa8a.png)

After Data Populator runs, the field named 'Icons/z-nested/icon glyphs/utility/... gets set to the value 'none.'

**Expected behavior**
I would not expect Data Populator to interact with that nested symbol at all, as the name of the item, and the names of its child items do not match any of the names in the JSON file I am using to populate.

**Environment (please complete the following information):**
 - macOS Version: macOS Mojave 10.14.2
 - Sketch Version: Sketch 52.5
 - Plugin Version: 3.0.3

**Comment by nitrada** [comment]
@tsheiner we’ll have a look!
