### ISSUE TITLE
Custom color based on data hex value

### ISSUE THREAD

**Issue by aiancuevc** [preciousforever/data-populator#172]
**Which version of the plugin are you using?**
[x] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Is your feature request related to a problem? Please describe.**
I'm customizing an artboard for each client, so in addition to text data it would be nice to be able to set the accent colors in hex and apply it to some layers (foreground color, background color)

**Describe the solution you'd like**
perhaps adding a filter in the name of a layer could set its foreground/background color

**Describe alternatives you've considered**
I data merge then manually set the colors for each artboard.

**Comment by nitrada** [comment]
please see #97
