### ISSUE TITLE
Data Populator for Figma?!

### ISSUE THREAD

**Issue by socon37** [preciousforever/data-populator#174]
**Which version of the plugin are you using?**
[ ] Data Populator for Sketch
[ X ] Data Populator for Adobe XD

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Integration with Figma!

**Describe alternatives you've considered**

**Additional context**

**Comment by nitrada** [comment]
no plans for a figma version in the foreseeable future.
