### ISSUE TITLE
Absolute image paths don't work

### ISSUE THREAD

**Issue by davestewart** [preciousforever/data-populator#175]
**Which version of the plugin are you using?**
[x] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Describe the bug**

Using absolute image paths appears not to work:

```
  {
    "title": "chrome.storage - Google Chrome",
    "icon": "/Volumes/Data/Work/Projects/Extensions/Tabnado/design/themes/icons/exist.png"
  },
```

The text populates, but the images don't.

Using relative image paths does work though.

**Expected behavior**
The images would be populated.

**Environment (please complete the following information):**
 - macOS Version: [macOS Sierra 10.12.6]
 - Sketch Version [Sketch 51.2]
 - Plugin Version [2.3.5 + 3.0.0]

**Additional context**
I tried also tried with with `file://` but that didn't work.

**Comment by lukewar** [comment]
I am having the same issue. I got it working only if file is in the same folder with sketch file. @davestewart you mentioned that relative path worked for you. Does that mean that you have your image in sub folder relative to sketch file?

**Comment by davestewart** [comment]
Hi Luke. I can't remember now, but I think so, yes.

**Comment by lukewar** [comment]
Hi Dave. I am asking because I can't get that working for me and I am thinking to figure out what am I doing wrong.

**Comment by davestewart** [comment]
Yep, it works for me:

![image](https://user-images.githubusercontent.com/132681/55098493-c707f180-50b5-11e9-948d-c9d5cecbb9c9.png)

```json
[
  {
    "title": "Icon 1",
    "icon": "icons/icon-01.jpg"
  },
  {
    "title": "Icon 2",
    "icon": "icons/icon-02.jpg"
  },
  {
    "title": "Icon 3",
    "icon": "icons/icon-03.png"
  }
]
```

Here's a zip with the structure and files I used:

- [icon test.zip](https://github.com/preciousforever/data-populator/files/3014532/icon.test.zip)

Make sure to:

1. Have a valid JSON file
2. Place and select the symbol on stage
3. Go Plugins > Data Populator > Populate with JSON
4. Choose the file
5. Update layout options

Good luck :)

**Comment by lukewar** [comment]
Yes, my bad. I thought that this path should be relative to sketch file not the JSON file.
Thank you for your help.

**Comment by davestewart** [comment]
It's a fair assumption!

**Comment by nitrada** [comment]
We'll add a hint to the documentation and close this issue.
