### ISSUE TITLE
Adding support for templating languages?

### ISSUE THREAD

**Issue by Simon-Tang** [preciousforever/data-populator#176]
**Which version of the plugin are you using?**
[X] Data Populator for Sketch
[ ] Data Populator for Adobe XD

Although it is simple and intuitive to use a flat object in JSON for populating the fields, there are some use cases where it might be helpful to use a templating language like [Liquid](https://github.com/Shopify/liquid). For instance, if we want to use loops and arrays.

Do you have any thoughts on how feasible it would be to add something like this?

**Comment by nitrada** [comment]
@Simon-Tang we have no plans to add something like this and have not yet looked into feasibility. Maybe yourself, or developers you know might be interested in contributing the feature?
