### ISSUE TITLE
Conditional Actions are not functioning

### ISSUE THREAD

**Issue by amardeeprai** [preciousforever/data-populator#177]
**Which version of the plugin are you using?**
[X ] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Describe the bug**
Conditional Actions are not functioning

**To Reproduce**
Steps to reproduce the behaviour:
1. Add `#hide[true]` `#show[true]` or `#delete[true]` to a layer or group
2. Run the data populator

**Expected behaviour**
The conditional action to run and the layer or group to either hide, show, or delete

**Screenshots**
![image](https://user-images.githubusercontent.com/10384977/55546900-18bd0700-56c8-11e9-82b3-218f546183b4.png)

**Environment (please complete the following information):**
 - macOS Mojave Version 10.14
 - Sketch Version 53.2
 - Plugin Version 3.0.3

**Comment by jeep84** [comment]
Same issue here:

**Environment (please complete the following information):**

macOS High Sierra 10.13.6
Sketch Version 55
Plugin Version 3.0.3

**Comment by mellis3** [comment]
Same problem here. Is there any movement on fixing this bug?

macOS Mojave 10.14.6
Sketch Version 62
Plugin Version 3.0.3

Steps to reproduce. 
1. Name a layer with #show[ false ]
or
1. Name a layer with #show[ "{age}" < 30 ]
or
Any variant on a condition

Nothing seems to work.

**Comment by marklanham** [comment]
I'm having this same issue on **Sketch Version 72.2 (124462)** with **macOS Big Sur v11.2.3 (20D91)**.

Have tried multiple ways such as applying it to a **layer group** and **symbol** using the following format: `#show["{example}"]` where `{example}` is set to `true` or `false` in the JSON data but nothing works.

**Comment by nitrada** [comment]
see https://github.com/preciousforever/data-populator/issues/220 – known issue, will be fixed once a budget is availabe
