### ISSUE TITLE
Sketch 55: Grouped text fields don't get populated

### ISSUE THREAD

**Issue by Basb** [preciousforever/data-populator#182]
**Which version of the plugin are you using?**
[X] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Describe the bug**
When you select an artboard and choose to populate, not all text with {} variables gets populated. Unclear if this has to do with grouping. Changing the layer order has impact on which texts get populated.

**To Reproduce**
I was unable to pinpoint the exact cause.

1. Open test.sketch in attached [test.zip](https://github.com/preciousforever/data-populator/files/3221041/test.zip)
2. Select artboard
3. Populate with test.json
4. Not all variable text gets populated (two out of three)

All variables on the artboard are in test.json.

**Expected behavior**
When I select an artboard, I expect all the variable text in that arboard to get populated with the data.

**Screenshots**
<img width="1393" alt="step1" src="https://user-images.githubusercontent.com/3246963/58386432-5d419080-7fef-11e9-9465-0f52ae5d83e8.png">
<img width="1396" alt="step2" src="https://user-images.githubusercontent.com/3246963/58386433-5d419080-7fef-11e9-9480-528f333df1dd.png">
<img width="1395" alt="step3" src="https://user-images.githubusercontent.com/3246963/58386434-5d419080-7fef-11e9-8ad5-3b3cd9e46190.png">

**Environment (please complete the following information):**
 - macOS Version: Mojave 10.14.5 (18F132)
 - Sketch Version: 55 (78076)
 - Plugin Version: 3.0.3

Other plugins (most of them are disabled):
<img width="521" alt="plugins" src="https://user-images.githubusercontent.com/3246963/58386458-a1cd2c00-7fef-11e9-9de2-c8df44777667.png">

**Comment by marsshall** [comment]
same for adobe XD

**Comment by nitrada** [comment]
II was able to reproduce with "test.sketch" and "test.json". It's a bug, apparently.
