### ISSUE TITLE
Loading data in to master component and refreshing his child's

### ISSUE THREAD

**Issue by AdamBiganovsky** [preciousforever/data-populator#184]
**Which version of the plugin are you using?**
[ ] Data Populator version 1.1.4

**Describe the solution you'd like**
I would like to be able populate data in Master Component which should refresh all his child's components used across project.

**Describe alternatives you've considered**

**Additional context**
When I'm trying to populate data in Master Component it will affect his child's for a second but then it will return to a default state with variables {variable0}{variable1}.

**Comment by AdamBiganovsky** [comment]
Not sure if it's even possible do it, maybe it's more problem in Adobe XD, but posting it anyway since if it would be possible it would be tremendously useful :)
Thanks for this great plugin anyway tho! 👍

**Comment by vandersonlb** [comment]
@AdamBiganovsky I have the same problem.
