### ISSUE TITLE
Plugin stop working on sketch 57.1?

### ISSUE THREAD

**Issue by PngTran** [preciousforever/data-populator#185]
**Which version of the plugin are you using?**
[ v3.0.3] Data Populator for Sketch

**Describe the bug**
Plugin was working perfectly previously and stops working on Sketch 57.1
Tested on previous version of Sketch and it works with 56

**Environment (please complete the following information):**
 - macOS Version: Mojave 10.14.5 (18F132)
 - Sketch Version: 57.1
 - Plugin Version: 3.0.3

**Comment by nitrada** [comment]
@PngTran do you still have this issue with the latest version of Sketch?
