### ISSUE TITLE
Plugin Broken in Sketch 58

### ISSUE THREAD

**Issue by acutedeveloper** [preciousforever/data-populator#188]
**Which version of the plugin are you using?**
[ 3.0.3 ] Data Populator for Sketch

**Describe the bug**
This afternoon I had updated to version 58 of Sketch, I found that the plugin was no longer behaving as expected. When I attempt to load data from a URL or JSON into symbols it will only populate one element at a time. If you attempted to update multiple fields inside of a symbol, it would update only one element

**To Reproduce**
1. Select multiple elements that are tagged
2. Click on Populate from JSON/URL
3. Populate
4. Result is only one element is updated

**Expected behavior**
I expect all elements that are tagged to populate with my JSON data as it was before v58

**Console**
I took a look at the Plugin Log.log in console. It revealed:

```
No WebView present. Event cannot be posted to the web UI.
```

**Environment:**
 - macOS Version:  macOS Mojave 10.14.6
 - Sketch Version Sketch 58
 - Plugin Version 3.0.3

**Additional context**
To finish the prototype I had to individually select single layers to populate them with data. Slow...but still faster that copy and pasting.lol!

**Comment by pushingvision** [comment]
This is also happening for me. Is there a timeline for a fix on this?

**Comment by nitrada** [comment]
@acutedeveloper @pushingvision do you still have this issue with the latest version of Sketch?
