### ISSUE TITLE
jakob.behrends@kaiser-x.com

### ISSUE THREAD

**Issue by kaiser-jakob** [preciousforever/data-populator#191]
**Which version of the plugin are you using?**
[x] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Describe the bug**
Since the latest update of sketch symbol overrides can not be used to map JSON data anymore.

**To Reproduce**
1. Create a symbol with a text layer in it
2. Name the text layer `content`
3. Add an instance of the symbol to the canvas
4. put `{text1}` ass a symbol override for "content"
5. load a JSON with `"text1": "test"`
6. the symbol override turns blank

**Expected behavior**
I expect the symbol override to be filled with the value of key `text1`.

**Screenshots**
![image](https://user-images.githubusercontent.com/27895008/70508321-8d392700-1b2e-11ea-85c6-c0c00a7a0c6e.png)

**Environment (please complete the following information):**
 - macOS Version: 10.14.6
 - Sketch Version 61
 - Plugin Version 3.0.3

**Additional context**
-

**Comment by nitrada** [comment]
@kaiser-jakob do you still have this issue with the latest version of Sketch? Also, can you try turning one of the "Contact Cards" in the Sketch Demo Document into a symbol and retry? Please let us know if it works.

https://www.datapopulator.com/sketch/
