### ISSUE TITLE
hangs when poulating

### ISSUE THREAD

**Issue by vthomw** [preciousforever/data-populator#193]
**Which version of the plugin are you using?**
[ ] Data Populator for Sketch
[x ] Data Populator for Adobe XD

**Describe the bug**
Data Populator hangs XD while populating on various occations. Killing XD is the only way out. Examples
1) when using / as text 
2) when using align center on buttons
3) both on Mac and Win

**To Reproduce**
1. Select artboard in XD 
2. Populate with JSON
3. select file
4. Populate
5. "populating" STOP .. runs forever

**Expected behavior**
it seems unstable, maybe a recompile of Data Populator Plugin will do the job

**Environment (please complete the following information):**
 - macOS/Win10 Version: newest
 - Adobe XD Version: newest
 - Plugin Version [1.1.4]

Btw: we want to integrate with LOCO

**Comment by CarolynSkalny-DMS** [comment]
I am experiencing the same issue.

**Comment by khaggerty-adev** [comment]
I think I am experience the same issue.

- Adobe XD 25.1.12.7 for Windows
- Using "Populate with JSON"
- JSON file is simple array of JSON objects with a single key-value pair (string)
- Trying to populate a text object inside of a component inside of a "Repeat Grid" element
- After selecting my "Repeat Grid" element and selecting my JSON file, the filepath does not appear left of the "Browse" button and the right pane is stuck "Loading data..." with the activity indicator
  - "Reload" doesn't do anything
  - Selecting "Populate" displays error message "**No file selected** Please select a JSON file to populate with."

**Comment by khaggerty-adev** [comment]
I solved my issue! I was being dumb and not using quotes around my keys in my JSON file.

I now have a separate issue where I am unable to use a different JSON file once one has already been used.
