### ISSUE TITLE
Feature Request: Allow to filter elements before populating

### ISSUE THREAD

**Issue by LennartHennigs** [preciousforever/data-populator#194]
**Which version of the plugin are you using?**
[x] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Is your feature request related to a problem? Please describe.**
I have a large dataset which contains different types of elements. Sometimes I'd like to be able to get only one type. For now I have to use different .json files which are "pre filtered".

**Describe the solution you'd like**
I'd like to be able to add a filter to my json data before the data gets populated.

**Describe alternatives you've considered**
Multiple .json files. But that's quite cumbersome...

**Additional context**
Even if it comes last: I love your plugin and thanks for sharing it publicly!

**Comment by LennartHennigs** [comment]
Any feedback?

**Comment by nitrada** [comment]
@LennartHennigs yeah, we hear you. though, it isn't something we're planning to add to Data Populator for the sake of keeping it simple and focussed on _populating data_. Nevertheless, we're thinking about ways how to manipulate/transform data between a data source (local JSON file or API URL) and the actual populating inside the design document.
