### ISSUE TITLE
Data Populator can't find keys inside components (Adobe XD)

### ISSUE THREAD

**Issue by khaggerty-adev** [preciousforever/data-populator#198]
**Which version of the plugin are you using?**
[x] Data Populator for Adobe XD

**Describe the bug**
When the key is inside of an Adobe XD component, Data Populator is unable to find it.

**Expected behavior**
Data Populator should be able to populate text even inside of components. This should work both for individual components and components inside of "Repeat Grid" elements.

**Environment (please complete the following information):**
 - Windows Version: 10 Pro (10.0.18363)
 - Adobe XD Version: 25.1.12.7 (Starter)
 - Plugin Version: ????? (not sure how to check)

**Comment by vandersonlb** [comment]
@khaggerty-adev I have the same problem.
