### ISSUE TITLE
Symbols do not populate, but layers do in Sketch 64

### ISSUE THREAD

**Issue by chrism** [preciousforever/data-populator#199]
**Which version of the plugin are you using?**
[ X ] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Describe the bug**
If I detach from a symbol then the data populates correctly, but kept as a symbol it does not work as expected.

**To Reproduce**
1. I have added a symbol with two fields I want to populate, one text `{message}`, one image `{image}` to an artboard.

<img width="161" alt="Screenshot 2020-03-26 at 14 58 50" src="https://user-images.githubusercontent.com/35488/77655192-620a0480-6f72-11ea-9916-44b866748bd2.png">

2. The JSON displays correctly in the data populator.

<img width="252" alt="Screenshot 2020-03-26 at 15 01 19" src="https://user-images.githubusercontent.com/35488/77655471-bdd48d80-6f72-11ea-8490-0c5632169004.png">

3. The data is not applied correctly.

4. However, if I detach the symbol so that they are layers, not a symbol.

<img width="179" alt="Screenshot 2020-03-26 at 15 03 24" src="https://user-images.githubusercontent.com/35488/77655635-f7a59400-6f72-11ea-8685-f7f74f98a5b6.png">

5. The data is populated correctly.

**Expected behavior**
I would expect that symbols could be populated, in the same way that layers are.

**Environment (please complete the following information):**
 - macOS Version: macOS Mojave 10.14.6
 - Sketch Version: Sketch Version 64 (93537)
 - Plugin Version: 3.0.3

**Additional context**
This is the first time I have used this plugin, so not sure if this was working before, or if I am doing something wrong.

**Comment by Cleecanth** [comment]
This is also true in the XD version of the plugin. I know on that end of things, this is actually a limitation of the XD api itself.

That said, some kind of error or warning would be useful.

**Comment by nitrada** [comment]
@chrism do you still have this issue with the latest version of Sketch? Also, can you try turning one of the "Contact Cards" in the Sketch Demo Document into a symbol and retry? https://www.datapopulator.com/sketch/

![image](https://user-images.githubusercontent.com/1927315/85949394-c87a3680-b956-11ea-845f-82059d583b37.png)

**Comment by nitrada** [comment]
> This is also true in the XD version of the plugin. I know on that end of things, this is actually a limitation of the XD api itself.
> That said, some kind of error or warning would be useful.

Yea, Components in Adobe XD are not yet supported (see https://github.com/preciousforever/data-populator/issues/198)
