### ISSUE TITLE
Local image path is not populating

### ISSUE THREAD

**Issue by nomadme** [preciousforever/data-populator#233]
**Which version of the plugin are you using?**
3.5.0 Data Populator for Adobe XD

**Describe the bug**
Can't populate local image that is in the same path with the data file.

**Expected behavior**
According to the doc, the image files should be in the same path as with the data.

**Environment (please complete the following information):**
 - macOS Version: 10.15.7
 - Adobe XD Version 34.2.12.2
 - Plugin Version 3.5.0

This is my data and the image structure:
```
.
├── build
│   ├── john_doe.jpg
├── john_doe.jpg
├── team_member.json
```

data:
```
[
  {
    "id": 1,
    "name": "John Doe",
    "bio": null,
    "image": "build/john_doe.jpg",
    "team_id": 6,
    "created_at": "2018-02-13 22:54:14",
    "updated_at": "2018-02-14 08:40:59",
    "title": null,
    "order": null,
    "active": true
  },
...
]
```

I tried the image path both places, one directly next to the data, and the one in the dir, specified in the data.image.

<img width="360" alt="Screen Shot 2020-11-12 at 4 32 34 PM" src="https://user-images.githubusercontent.com/6267271/99004791-48b7c780-2505-11eb-978c-de88e6d13837.png">

**Comment by lspg** [comment]
+1, i got the same problem, using xd on mac os catalina or windows 10 gives the same result. It seems populating local images doesn't work under XD.

**Comment by aperezbaena** [comment]
Local files are not working for me. Using Adobe XD v54.1.12.1 with Data Populator v4.0.3 on macOS Catalina v10.15.7.

Developer console error is as follows:
`Failed to get local image [Error: Could not find an entry with name 'data sources/cdbe9047-9571-44c3-ab23-c31809087108/images/{Icon}' in '/Users/_username_/Library/Application Support/Adobe/UXP/PluginsStorage/SPRK/External/1c0ce86b/PluginData/']`

Tried moving the images to that location. Fallback image and static image path work fine, however using placeholder is not working.
