### ISSUE TITLE
Auto-height does not work for text or paragraphs

### ISSUE THREAD

**Issue by NaderMozaffari** [preciousforever/data-populator#235]
**Which version of the plugin are you using?**
[✓] Data Populator for Sketch

**Describe the bug**
i want add a multiline text via auto height option
but Auto-height does not work for text in plugin
I use RTL texts

**To Reproduce**
1. Add text for exp '{p.0.info}' this is a pragraphs(text multi line)
2. Click on 'Populate again' for get data
3. Shows the paragraph as a short line 
3. auto height option is on, but after clicking it's not working 

**Expected behavior**
I want to show the paragraph in a multiline

**Environment (please complete the following information):**
 - macOS Version: [macOS Catalina 10.15.3]
 - Sketch Version [Sketch 70.3]
 - Plugin Version [3.5.2]

**Comment by nitrada** [comment]
@NaderMozaffari have you tried using the multiline approach described [here](https://www.datapopulator.com/documentation/#multiline-text-layers)?

**Comment by NaderMozaffari** [comment]
> @NaderMozaffari have you tried using the multiline approach described [here](https://www.datapopulator.com/documentation/#multiline-text-layers)?

I was more comfortable with the previous method without using l-n

**Comment by nitrada** [comment]
what previous method are you referencing – can you describe?
