### ISSUE TITLE
Parse/Manipulate Data

### ISSUE THREAD

**Issue by CorporateDrone** [preciousforever/data-populator#242]
**Which version of the plugin are you using?**
[ ] Data Populator for Sketch
[X ] Data Populator for Adobe XD

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to parse/manipulate JSON data. For example, we have timestamps that look like this "2021-03-09T14:53:31.859+0000" I would like the ability to write JS inbetween the curly brackets so I can format the data into a more user-friendly format in the mockups. 

**Describe alternatives you've considered**
None available

**Comment by nitrada** [comment]
@CorporateDrone wait for the upcoming next release!

**Comment by nitrada** [comment]
@CorporateDrone try building the latest code locally on your end and try `{time stamp | date LOCALE FORMAT}`

**Comment by nitrada** [comment]
@CorporateDrone you can now also download the [latest release](https://www.datapopulator.com/releases/data-populator-v4.0.1.xdx) of the XD plugin. The [documentation](https://www.datapopulator.com/documentation/#available-filters) is still work in progress, but you get the idea. Let us know what you think!

**Comment by CorporateDrone** [comment]
Awesome! I'll check it out and let you know.
