### ISSUE TITLE
Bug- Data not populating in placeholders

### ISSUE THREAD

**Issue by GodDevs** [preciousforever/data-populator#250]
**Which version of the plugin are you using?**
[X] Data Populator for Sketch
[✓] Data Populator for Adobe XD

**Describe the bug**
After clicking on populate, text is not showing or we can say that the data is not populating.
But in the preview its giving output.

**To Reproduce**

**Expected behavior**
The data should be populated in the placeholder

**Screenshots**
The placeholder is empty after clicking on populate
But the data preview is working

![WhatsApp Image 2021-05-24 at 1 52 26 PM](https://user-images.githubusercontent.com/84652909/119319111-ab99d080-bc97-11eb-94b0-24adb9398e6f.jpeg)
![WhatsApp Image 2021-05-24 at 1 52 11 PM](https://user-images.githubusercontent.com/84652909/119319132-b0f71b00-bc97-11eb-8000-f666b83c9829.jpeg)

**Environment (please complete the following information):**
 - macOS Version: [e.g. macOS High Sierra 10.13.5]
 - Sketch Version [e.g. Sketch 52.2] or Adobe XD Version [e.g. Adobe XD 13.0.0.0]
 - Plugin Version [e.g. 3.0.0]

I use it in windows
Windows 10 pro
adobe xd 2020
latest plugin version

**Additional context**

**Comment by GodDevs** [comment]
Its my earnest request to the developers to solve this issue as fast as possible

**Comment by nitrada** [comment]
@GodDevs please send your XD document to feedback@datapopulator.com for investigation

**Comment by GodDevs** [comment]
today it is populating the data. thanks devs for the quick fix

**Comment by nitrada** [comment]
@GodDevs nothing has been changed, actually ;-)
