### ISSUE TITLE
Iterating over a group

### ISSUE THREAD

**Issue by iansoper** [preciousforever/data-populator#42]
I was thinking if you took a layer group and allowed iterating inside of the group like a handlebars template would do:

``` handlebars
{{#each dataObject }}
   {{name}}
{{/each}}
```

The layer group could be named `{dataObject}` and the text layer would be `{name}` that way you could iterate over an array of objects and then populate the data inside it. Does that make sense?

**Comment by nitrada** [comment]
@rockitbaby @lukasondrej  thoughts?

**Comment by RYOHOI** [comment]
Yeah, that would be nice.

<img width="236" alt="screen shot 2016-04-27 at 12 08 35" src="https://cloud.githubusercontent.com/assets/5955526/14841507/ea647392-0c70-11e6-9779-8d8b788bfb2f.png">

What I'm just thinking about is like this. (Sorry about the Chinese)

**Comment by filipux** [comment]
This feature is the only thing that prevents us from using real json-data in all our apps. When it gets implemented this plugin really becomes a game changer!


`{
    "name": "My chainsaw",
    "image": "img/chainsaw.png",
    "cards": [{
        "caption": "Battery level",
        "text": "58%"
    }, {
        "caption": "RPM",
        "text": "3600"
    }, {
        "caption": "Runtime",
        "text": "13hrs"
    }]
}`

**Comment by metalhaze** [comment]
```
"users": {
   "Alex": {},
   "Bob": {},
   "Dave": {},
   "Phil": {}
}
```
I would love to be able to just type "users" once in my design file, have this tool iterate over the "users" object keys, and return all the user names to automatically populate multiple text layers in my design file (maybe in conjunction with the Repeat Grid tool in Adobe XD?) That way, I don't have to do this in XD layers panel (slowly, painfully, and manually)

```
Layer 1: {users.Alex}
Layer 2: {users.Bob}
Layer 3: {users.Dave}
Layer 4: {users.Phil}
```
