### ISSUE TITLE
Selecting which set of data : Feature Request

### ISSUE THREAD

**Issue by russgoodman** [preciousforever/data-populator#68]
When I have several objects/sets of data in my JSON file, it would be really useful to be able to select which individual object/sets of data I want to populate a single component. This is the one killer feature that I would really love.

**Comment by nitrada** [comment]
hey @russgoodman, can you elaborate a bit more? give an example?

**Comment by russgoodman** [comment]
For sure. I'm making a part of an interface that has five videos players. There's an image, a title, the length of time per video, and I have 20 sets of video data in my JSON file. I'd like to be able to select a single video component, and be able to select which of the 20 sets of video data in my JSON file I would like to apply to this video component. Currently I would either need to have 20 JSON files, or produce 20 components then select the one that I wanted.

If there was a picker after selecting your JSON file, that'd be very good. If you want further explanation/clarification I'll be happy to expand further. I'm using this plugin a lot. We've even written a script that makes a Google Sheet output perfect JSON for the plugin so the rest of the team can contribute to the content in our designs.

**Comment by lukasondrej** [comment]
I've had some ideas about this too @russgoodman. I'd say a nice way to do it could also be just adding something like `[2]` or `@[2]` to the name of the layer/group you're populating to select the object at index 2 in the data array. What do you think about that?

**Comment by russgoodman** [comment]
@lukasondrej I think it would be preferable to decouple the specific data request from the vector. Because there are various sets of data in the json file I'd think I'd be more likely to be using symbols. Although I can see the Data Populator UI getting complex if you're populating repetitive pieces design components. I'm not sure where more difficulty lies here, from a development perspective.

**Comment by patowod** [comment]
This is such a great plugin - but being able to specifically tie a layer/group to an object would be a very valuable addition, especially when thinking about maintaining something like a copybook with contents across multiple screen variations, for example. Is there any chance that this will be implemented in the near future @lukasondrej ?
