### ISSUE TITLE
Feature Request: Pull from multiple JSON files

### ISSUE THREAD

**Issue by H3GGERS** [preciousforever/data-populator#87]
It would be amazing if I could populate data from multiple JSON files. My use-case is that I have symbols with several different text layers that get populated using your plugin. Some of those text layers need to point to different JSON files (basically I'm too lazy to try an configure a master file). From what I can tell, the plugin can only point to one file so if I repopulate, i get "undefined" for anything thats not pointing to the correct JSON

**Comment by GeorgeHinch** [comment]
This would actually be super useful. I often find myself using multiple json files and it's weird that it overwrites previous population when you populate it with another json file. Then again, maybe I'm just using it wrong?
