### ISSUE TITLE
Feature Request: Allow Placeholders in Overrides

### ISSUE THREAD

**Issue by skipjack** [preciousforever/data-populator#94]
Based off a conversation with @nitrada in #52...

The current behavior for using this plugin with symbols allows using the `{...}` placeholders within layer names (and layer content?) as such:

![image](https://cloud.githubusercontent.com/assets/8988697/24961499/f407447e-1f66-11e7-8231-8bf856d75361.png)

However, I'm in a scenario where I don't want to lock my symbols (nested symbols here) to a particular block of data. For example, let's say I have a grid and each column's cells are nested symbols (like normal content, a dropdown, a link, etc). Then, each cell should receive a different property of the JSON data **without locking the nested symbol to the given property**. In this case, instead of having to duplicate or detach my dropdown or content symbols, it would be great to be able to specify the placeholder (`{...}`) **within the override rather than the layer name** like so:

![image](https://cloud.githubusercontent.com/assets/8988697/24962103/dbfa2886-1f68-11e7-9f5b-bd04a7c3e943.png)

This approach allows certain symbols, like the dropdown and link, to be agnostic of the data they're being populated with. 

@nitrada I think this should sum it up pretty well but let me know if anything needs clarification. I looked through the `demo.sketch`, which did illuminate some of the features a bit better but unfortunately I still couldn't find a way to tackle this use case with the current feature set.

**Comment by nitrada** [comment]
@lukasondrej what do you think?

**Comment by mhcom** [comment]
Any news on this? Would be a killer feature to create truly modular Sketch files and test them with real data in no time at all!

**Comment by nitrada** [comment]
we're still thinking about it… :)

**Comment by mhcom** [comment]
Let us know if we can support the thought process (why it makes sense, etc.) or support it in any other way! :)

**Comment by bottledsmoke** [comment]
I would love this feature as well. If you need any help implementing it, I can help out.

**Comment by nitrada** [comment]
@bottledsmoke feel free to fork off and PR :)

**Comment by nitrada** [comment]
@bottledsmoke still up for helping out to make it work? :)

**Comment by nitrada** [comment]
@mhcom feel free to contribute. we'll evaluate any PR! :)

**Comment by nitrada** [comment]
@skipjack @bottledsmoke @mhcom we're trying to get this working for v3.0.3!

**Comment by nitrada** [comment]
@skipjack please check out v3.0.3!
https://www.datapopulator.com/sketch/changelog.html

**Comment by skipjack** [comment]
Awesome @nitrada and thanks to anyone else who helped push this forward!
